import Image from "next/image";
import Link from "next/link";
import { recentReleases, emergingFocusAreas } from "@/lib/releases";
import { ReleaseCard } from "@/components/ReleaseCard";

const learningResources = [
  {
    title: "Dart 3 Language Tour",
    description: "Catch up on records, pattern matching, and sealed classes with updated examples and migration strategies.",
    url: "https://dart.dev/language"
  },
  {
    title: "Flutter Forward Sessions",
    description: "Watch recorded talks covering graphics roadmap, Material 3 design system, and multiplatform case studies.",
    url: "https://flutter.dev/events/flutter-forward"
  },
  {
    title: "DevTools Deep Dive",
    description: "Explore new frame analysis, shader warmup, memory search, and CPU profiler views to tighten feedback loops.",
    url: "https://docs.flutter.dev/tools/devtools/overview"
  }
];

const quickWins = [
  "Adopt Material 3 `ThemeData` to unlock dynamic color harmonization and adaptive scaffolds.",
  "Switch existing iOS apps to Impeller (default as of 3.19) and validate animation smoothness across your navigation flows.",
  "Leverage `go_router` 14 with pattern matching routes for type-safe navigation generated by Dart macros preview.",
  "Wire DevTools' network page to observe gRPC/HTTP traces for backend call optimization."
];

export default function Page() {
  return (
    <main className="mx-auto flex min-h-screen max-w-6xl flex-col gap-24 px-6 py-12 sm:px-10 lg:px-16">
      <section className="grid gap-10 lg:grid-cols-[1.3fr_1fr] lg:items-center">
        <div className="flex flex-col gap-6">
          <span className="inline-flex max-w-max items-center gap-2 rounded-full border border-flutterTeal/50 bg-flutterTeal/10 px-3 py-1 text-xs font-semibold tracking-[0.3em] text-flutterTeal">
            FLUTTER UPDATE BRIEF
          </span>
          <h1 className="text-4xl font-bold leading-tight text-white md:text-5xl">
            What&apos;s new in Flutter for developers
          </h1>
          <p className="max-w-2xl text-lg leading-relaxed text-slate-300">
            Stay ahead of the curve with highlights from the most recent stable releases, actionable migration tips, and focus
            areas that will help your Flutter apps perform better across mobile, web, and desktop.
          </p>
          <div className="flex flex-wrap gap-4">
            <Link
              href="https://docs.flutter.dev/release/whats-new"
              className="inline-flex items-center justify-center rounded-full bg-flutterTeal px-6 py-3 text-sm font-semibold uppercase tracking-wide text-slate-950 transition hover:bg-teal-300"
            >
              Full release notes
            </Link>
            <Link
              href="https://flutter.dev/community"
              className="inline-flex items-center justify-center rounded-full border border-white/20 px-6 py-3 text-sm font-semibold uppercase tracking-wide text-slate-100 transition hover:border-flutterTeal/50 hover:text-flutterTeal"
            >
              Join the community
            </Link>
          </div>
        </div>
        <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-8 shadow-2xl shadow-black/40">
          <div className="absolute left-1/2 top-0 h-48 w-[110%] -translate-x-1/2 rounded-full bg-flutterTeal/20 blur-3xl" />
          <div className="relative flex h-full flex-col justify-between gap-6">
            <Image
              src="https://storage.googleapis.com/codex-public-assets/flutter-blend.png"
              alt="Flutter abstract graphic"
              width={480}
              height={320}
              className="rounded-2xl border border-white/10 object-cover"
              priority
            />
            <p className="text-sm text-slate-300">
              Impeller now powers iOS production apps, delivering consistent frame pacing and eliminating shader compilation
              jank. Start validating your custom shaders today.
            </p>
            <div className="flex items-center justify-between text-xs font-medium text-slate-400">
              <span>Last updated: February 2024</span>
              <span>Channel: Stable</span>
            </div>
          </div>
        </div>
      </section>

      <section className="flex flex-col gap-10">
        <header className="flex flex-col gap-3">
          <h2 className="text-3xl font-semibold text-white">Recent releases</h2>
          <p className="max-w-3xl text-base text-slate-300">
            The Flutter team ships a stable release every quarter. Here are the standout improvements you should prioritize as
            you plan your roadmap.
          </p>
        </header>
        <div className="grid gap-8 md:grid-cols-2">
          {recentReleases.map((release) => (
            <ReleaseCard key={release.version} release={release} />
          ))}
        </div>
      </section>

      <section className="grid gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center">
        <div className="relative flex flex-col gap-6 overflow-hidden rounded-3xl border border-white/10 bg-slate-900/70 p-8 shadow-inner shadow-black/40">
          <h3 className="text-2xl font-semibold text-white">Quick wins this sprint</h3>
          <ul className="flex flex-col gap-5 text-base leading-relaxed text-slate-200">
            {quickWins.map((tip) => (
              <li key={tip} className="relative pl-6">
                <span className="absolute left-0 top-2 h-1.5 w-1.5 rounded-full bg-flutterTeal" />
                {tip}
              </li>
            ))}
          </ul>
        </div>
        <div className="flex flex-col gap-6">
          <h3 className="text-2xl font-semibold text-white">Focus areas to watch</h3>
          <div className="grid gap-6">
            {emergingFocusAreas.map((area) => (
              <article key={area.title} className="rounded-3xl border border-white/10 bg-slate-900/60 p-6">
                <h4 className="text-xl font-semibold text-flutterTeal">{area.title}</h4>
                <p className="mt-2 text-sm text-slate-300">{area.summary}</p>
                <ul className="mt-4 flex flex-col gap-2 text-sm text-slate-200">
                  {area.actions.map((action) => (
                    <li key={action} className="flex gap-3">
                      <span className="mt-2 h-1.5 w-1.5 flex-none rounded-full bg-flutterTeal/70" />
                      <span>{action}</span>
                    </li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="flex flex-col gap-8 rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 via-slate-900/30 to-slate-950 p-10">
        <header className="flex flex-col gap-3">
          <h3 className="text-2xl font-semibold text-white">Level up with fresh resources</h3>
          <p className="text-base text-slate-300">
            Dive into the most helpful docs, conference sessions, and tooling walkthroughs to keep your skills sharp.
          </p>
        </header>
        <div className="grid gap-6 md:grid-cols-3">
          {learningResources.map((resource) => (
            <Link
              key={resource.url}
              href={resource.url}
              className="group rounded-3xl border border-white/10 bg-slate-900/70 p-6 transition hover:border-flutterTeal/50 hover:bg-slate-900"
            >
              <h4 className="text-lg font-semibold text-white group-hover:text-flutterTeal">{resource.title}</h4>
              <p className="mt-3 text-sm text-slate-300">{resource.description}</p>
              <span className="mt-4 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-flutterTeal">
                Explore
              </span>
            </Link>
          ))}
        </div>
      </section>

      <section className="flex flex-col gap-6 rounded-3xl border border-flutterTeal/40 bg-flutterTeal/10 p-10 text-slate-100">
        <h3 className="text-2xl font-semibold text-white">Keep shipping with confidence</h3>
        <p className="text-base leading-relaxed text-slate-200">
          Update to the latest stable channel, run `flutter doctor`, then validate critical journeys with integration tests
          before publishing. Don&apos;t forget to monitor crash analytics and shader warmup metrics post-release.
        </p>
        <div className="flex flex-wrap gap-4 text-sm font-semibold uppercase tracking-wide">
          <span className="rounded-full border border-white/30 px-4 py-2">CI ready</span>
          <span className="rounded-full border border-white/30 px-4 py-2">Impeller default</span>
          <span className="rounded-full border border-white/30 px-4 py-2">Material 3</span>
        </div>
      </section>
    </main>
  );
}
